# Generated by Django 4.2.27 on 2026-02-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Agent名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('skills', models.JSONField(default=list, verbose_name='技能列表')),
                ('price_per_task', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单任务价格')),
                ('reputation', models.FloatField(default=5.0, verbose_name='信誉分')),
                ('total_tasks_completed', models.IntegerField(default=0, verbose_name='完成任务数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['-reputation', '-total_tasks_completed'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='1-10分', verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='agents.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'ordering': ['-created_at'],
            },
        ),
    ]
